// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package templateclient

import (
	"net/http"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type TemplateClient interface {
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli *http.Client, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) TemplateClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

var DocumentOperationNames = map[string]string{}
